CREATE TABLE IF NOT EXISTS "user"
(
    id               bigint primary key generated by default as identity,
    user_type        text                     NOT NULL default '',
    email            text                     NOT NULL default '',
    password         text                     NOT NULL default '',
    name             text                     NOT NULL default '',
    birth_date       date                     NOT NULL,
    cpf              text                              default '',
    cnpj             text                              default '',
    telephone        text                     NOT NULL default '',
    address          TEXT                     NOT NUll default '',
    number           TEXT                     NOT NULL default '',
    complement       TEXT                              default '',
    city             TEXT                     NOT NULL default '',
    neighborhood     TEXT                              default '',
    state            TEXT               NOT NULL default '',
    cep              TEXT                     NOT NULL default '',
    creation_date    timestamp with time zone NOT NULL default now(),
    last_update_date timestamp with time zone NOT NULL default now()
);

CREATE TABLE IF NOT EXISTS qualification
(
    id   bigint primary key generated by default as identity,
    name text NOT NULL default ''
);

CREATE TABLE IF NOT EXISTS user_qualification_link
(
    user_id bigint NOT NULL,
    qualification_id   bigint NOT NULL,

    FOREIGN KEY (user_id)
        REFERENCES "user" (id),

    FOREIGN KEY (qualification_id)
        REFERENCES qualification (id)
);

CREATE TABLE IF NOT EXISTS opportunity_cause
(
    id   bigint primary key generated by default as identity,
    name text NOT NULL default ''
);

CREATE TABLE IF NOT EXISTS volunteer_opportunity
(
    id                       bigint primary key generated by default as identity,
    institution_id           bigint                   NOT NULL,
    name                     text                     NOT NULL default '',
    description              text                              default '',
    opportunity_date         date                     NOT NULL,
    address                  TEXT                     NOT NUll default '',
    number                   TEXT                     NOT NULL default '',
    complement               TEXT                              default '',
    city                     TEXT                     NOT NULL default '',
    neighborhood             TEXT                              default '',
    state                    TEXT              NOT NULL default '',
    cep                      TEXT                     NOT NULL default '',
    creation_date            timestamp with time zone NOT NULL default now(),
    last_update_date         timestamp with time zone NOT NULL default now(),

    FOREIGN KEY (institution_id)
        REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS qualification_opportunity_link
(
    opportunity_id bigint NOT NULL,
    qualification_id   bigint NOT NULL,

    FOREIGN KEY (opportunity_id)
        REFERENCES volunteer_opportunity (id),

    FOREIGN KEY (qualification_id)
        REFERENCES qualification (id)
);

CREATE TABLE IF NOT EXISTS cause_opportunity_link
(
    opportunity_id bigint NOT NULL,
    cause_id       bigint NOT NULL,

    FOREIGN KEY (opportunity_id)
        REFERENCES volunteer_opportunity (id),

    FOREIGN KEY (cause_id)
        REFERENCES opportunity_cause (id)
);

CREATE TABLE IF NOT EXISTS participation_certificate
(
    id                       bigint primary key generated by default as identity,
    candidate_id             bigint                   NOT NULL,
    volunteer_opportunity_id bigint                   NOT NULL,
    creation_date            timestamp with time zone NOT NULL default now(),

    FOREIGN KEY (candidate_id)
        REFERENCES "user" (id),

    FOREIGN KEY (volunteer_opportunity_id)
        REFERENCES volunteer_opportunity (id)
);
