namespace WeCare.Domain.Models;

public enum OpportunityCauseId
{
    POLITICS = 1,
    CITIZEN_PARTICIPATION = 2,
    FIGHT_AGAINST_HUNGER = 3,
    FIGHT_AGAINST_POVERTY = 4,
    CONSCIOUS_CONSUMPTION = 5,
    CHILDREN_AND_YOUTH = 6,
    CULTURE_SPORTS_AND_ART = 7,
    COMMUNITY_DEVELOPMENT = 8,
    EDUCATION = 9,
    RACIAL_EQUITY = 10,
    SPORTS = 11,
    ELDERLY = 12,
    YOUTH = 13,
    LGBTI = 14,
    ENVIRONMENT = 15,
    URBAN_MOBILITY = 16,
    WOMEN = 17,
    DISABLED_PEOPLE = 18,
    HOMELESS_POPULATION = 19,
    INDIGENOUS_PEOPLE = 20,
    ANIMAL_PROTECTION = 21,
    REFUGEES = 22,
    HEALTH = 23,
    SUSTAINABILITY = 24,
    PROFESSIONAL_TRAINING = 25
}