@startuml
class Candidate {
    + Cpf : string <<get>> <<set>>
    + BirthDate : DateOnly <<get>> <<set>>
}
User <|-- Candidate
Candidate --> "CausesCandidateIsInterestedIn" OpportunityCause : "0..*"
@enduml
