@startuml
class ParticipationCertificate {
    + Id : long <<get>> <<set>>
    + AuthenticityCode : string <<get>> <<set>>
    + RegistrationId : long <<get>> <<set>>
    + CreationDate : DateTime <<get>> <<set>>
}
ParticipationCertificate --> "Registration" OpportunityRegistration
@enduml
