@startuml
class VolunteerOpportunity {
    + Id : long <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Street : string <<get>> <<set>>
    + Number : string <<get>> <<set>>
    + Complement : string <<get>> <<set>>
    + City : string <<get>> <<set>>
    + Neighborhood : string <<get>> <<set>>
    + State : State <<get>> <<set>>
    + PostalCode : string <<get>> <<set>>
    + OpportunityDate : DateTime <<get>> <<set>>
    + CreationDate : DateTime <<get>> <<set>>
    + LastUpdateDate : DateTime? <<get>> <<set>>
    + Enabled : bool <<get>> <<set>>
    + InstitutionId : long <<get>> <<set>>
    + Institution : Institution? <<get>> <<set>>
    + HasAlreadyHappened() : bool
}
VolunteerOpportunity --> "Causes" OpportunityCause : 0..*
VolunteerOpportunity o-> "Registrations" OpportunityRegistration : 0..*
@enduml
